name: Cleanup Old Images

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  RETENTION_DAYS: 14

jobs:
  get-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.packages.outputs.list }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Get package list from registry
        id: packages
        run: |
          # Get base image packages
          PACKAGES='["mcp-python-base", "mcp-node-base"]'
          
          # Add server packages from registry
          SERVERS=$(jq -r '.servers | to_entries[] | select(.value.supported == true) | "mcp-" + .key' servers/registry.json | jq -R -s -c 'split("\n")[:-1]')
          
          # Combine base and server packages
          ALL_PACKAGES=$(echo $PACKAGES | jq --argjson servers "$SERVERS" '. + $servers')
          
          echo "Packages to clean: $ALL_PACKAGES"
          echo "list=$ALL_PACKAGES" >> $GITHUB_OUTPUT

  cleanup:
    needs: get-packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package: ${{ fromJson(needs.get-packages.outputs.packages) }}
    steps:
      - name: Delete old PR images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package }}
          package-type: container
          min-versions-to-keep: 0
          delete-only-pre-release-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
          # Delete PR-tagged images older than retention period
          ignore-versions: '^(?!.*-pr-\d+).*$'
          older-than: ${{ env.RETENTION_DAYS }} days

      - name: Delete old weekly images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package }}
          package-type: container
          min-versions-to-keep: 4  # Keep last 4 weekly builds
          delete-only-pre-release-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
          # Only target weekly builds
          ignore-versions: '^(?!.*weekly-).*$'
          
      - name: Delete old commit-tagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package }}
          package-type: container
          min-versions-to-keep: 10  # Keep last 10 commit-tagged builds
          delete-only-pre-release-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
          # Only target commit SHA tags (7 characters)
          ignore-versions: '^(?![a-f0-9]{7}$).*$'
          older-than: ${{ env.RETENTION_DAYS }} days
          
      - name: List remaining versions
        run: |
          echo "Remaining versions for ${{ matrix.package }}:"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/orgs/${{ github.repository_owner }}/packages/container/${{ matrix.package }}/versions" \
            --jq '.[].metadata.container.tags[]' | sort -u || echo "No versions found"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}