name: Sync MCP Repository Commits

on:
  workflow_dispatch:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'

jobs:
  sync-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Sync MCP repository commits
        run: |
          echo "Syncing MCP repository commits..."
          SYNC_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Create a temporary file for the updated registry
          cp servers/registry.json servers/registry.json.tmp
          
          # Function to get latest commit from a GitHub repo
          get_latest_commit() {
            local repo=$1
            local path=$2
            
            # Extract owner and repo name from URL
            if [[ $repo =~ github\.com/([^/]+)/([^/]+) ]]; then
              owner="${BASH_REMATCH[1]}"
              repo_name="${BASH_REMATCH[2]}"
              
              # Remove .git suffix if present
              repo_name="${repo_name%.git}"
              
              # Handle URLs with /tree/main/path
              if [[ $repo =~ /tree/main/(.+)$ ]]; then
                path="${BASH_REMATCH[1]}"
                repo_url="https://github.com/$owner/$repo_name"
              else
                repo_url="$repo"
              fi
              
              echo "Fetching commit for $owner/$repo_name${path:+ path: $path}" >&2
              
              # Use GitHub API to get the latest commit
              if [ -n "$path" ]; then
                # Get commit for specific path
                commit=$(curl -s "https://api.github.com/repos/$owner/$repo_name/commits?path=$path&per_page=1" | jq -r '.[0].sha // empty')
              else
                # Get latest commit for entire repo
                commit=$(curl -s "https://api.github.com/repos/$owner/$repo_name/commits?per_page=1" | jq -r '.[0].sha // empty')
              fi
              
              if [ -n "$commit" ]; then
                echo "$commit"
              else
                echo "null"
              fi
            else
              echo "null"
            fi
          }
          
          # Function to get latest release version from a GitHub repo
          get_latest_release() {
            local repo=$1
            
            # Extract owner and repo name from URL
            if [[ $repo =~ github\.com/([^/]+)/([^/]+) ]]; then
              owner="${BASH_REMATCH[1]}"
              repo_name="${BASH_REMATCH[2]}"
              
              # Remove .git suffix if present
              repo_name="${repo_name%.git}"
              
              # Handle URLs with /tree/main/path
              if [[ $repo =~ /tree/main/(.+)$ ]]; then
                repo_url="https://github.com/$owner/$repo_name"
              else
                repo_url="$repo"
              fi
              
              echo "Fetching latest release for $owner/$repo_name" >&2
              
              # Get latest release
              release=$(curl -s "https://api.github.com/repos/$owner/$repo_name/releases/latest" | jq -r '.tag_name // empty')
              
              if [ -n "$release" ]; then
                echo "$release"
              else
                echo "null"
              fi
            else
              echo "null"
            fi
          }
          
          # Process each server dynamically from registry
          echo "Processing servers from registry..."
          
          # Get list of supported servers
          SERVERS=$(jq -r '.servers | to_entries[] | select(.value.supported == true) | .key' servers/registry.json)
          
          for server in $SERVERS; do
            echo "Updating $server server..."
            
            # Get repository URL from registry
            REPO_URL=$(jq -r ".servers.$server.repository" servers/registry.json)
            
            if [ "$REPO_URL" != "null" ] && [ -n "$REPO_URL" ]; then
              # Get the latest commit
              COMMIT=$(get_latest_commit "$REPO_URL")
              
              # Get the latest release version
              RELEASE=$(get_latest_release "$REPO_URL")
              
              # Update the server's commit, release version and sync date
              jq --arg server "$server" --arg commit "$COMMIT" --arg release "$RELEASE" --arg date "$SYNC_DATE" \
                '.servers[$server].gitCommit = $commit | .servers[$server].releaseVersion = $release | .servers[$server].lastSync = $date' \
                servers/registry.json.tmp > servers/registry.json.tmp2
              mv servers/registry.json.tmp2 servers/registry.json.tmp
              
              echo "$server server commit: $COMMIT, release: $RELEASE"
            else
              echo "Skipping $server - no repository URL"
            fi
          done
          
          # Update the main updated timestamp
          jq --arg date "$SYNC_DATE" '.updated = $date' \
            servers/registry.json.tmp > servers/registry.json.tmp2
          mv servers/registry.json.tmp2 servers/registry.json.tmp
          
          # Move the updated file back
          mv servers/registry.json.tmp servers/registry.json
          
          echo "Sync completed at $SYNC_DATE"
      
      - name: Check for changes
        id: check-changes
        run: |
          if git diff --exit-code servers/registry.json; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Registry has changes"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Update README if needed
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          # Update README with latest server information
          ./scripts/generate-readme.sh
          
          # Check if README changed
          if ! git diff --exit-code README.md; then
            git add README.md
            README_UPDATED=true
          fi
      
      - name: Commit and push changes
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git add servers/registry.json
          if [ "$README_UPDATED" == "true" ]; then
            git commit -m "chore: sync MCP repository commits and update README [skip ci]"
          else
            git commit -m "chore: sync MCP repository commits [skip ci]"
          fi
          git push origin main
      
      - name: Trigger builds if commits changed
        if: steps.check-changes.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-servers.yml',
              ref: 'main'
            });